export const objective = [
  { id: "1", label: "K00.0", description: "Anodontia" },
  { id: "2", label: "K00.1", description: "Supernumerary teeth" },
  {
    id: "3",
    label: "K00.2",
    description: "Abnormalities of size and form of teeth",
  },
  { id: "4", label: "K00.3", description: "Mottled teeth" },
  { id: "5", label: "K00.4", description: "Disturbances in tooth formation" },
  {
    id: "6",
    label: "K00.5",
    description:
      "Hereditary disturbances in tooth structure, not elsewhere classified",
  },
  { id: "7", label: "K00.6", description: "Disturbances in tooth eruption" },
  { id: "8", label: "K00.7", description: "Teething syndrome" },
  {
    id: "9",
    label: "K00.8",
    description: "Other disorders of tooth development",
  },
  {
    id: "10",
    label: "K00.9",
    description: "Disorder of tooth development, unspecified",
  },
  { id: "11", label: "K01.0", description: "Embedded teeth" },
  { id: "12", label: "K01.1", description: "Impacted teeth" },
  { id: "13", label: "K02.0", description: "Caries limited to enamel" },
  { id: "14", label: "K02.1", description: "Caries of dentine" },
  { id: "15", label: "K02.2", description: "Caries of cementum" },
  { id: "16", label: "K02.3", description: "Arrested dental caries" },
  { id: "17", label: "K02.4", description: "Odontoclasia" },
  { id: "18", label: "K02.5", description: "Caries with pulp exposure" },
  { id: "19", label: "K02.8", description: "Other dental caries" },
  { id: "20", label: "K02.9", description: "Dental caries, unspecified" },
  { id: "21", label: "K03.0", description: "Excessive attrition of teeth" },
  { id: "22", label: "K03.1", description: "Abrasion of teeth" },
  { id: "23", label: "K03.2", description: "Erosion of teeth" },
  { id: "24", label: "K03.3", description: "Pathological resorption of teeth" },
  { id: "25", label: "K03.4", description: "Hypercementosis" },
  { id: "26", label: "K03.5", description: "Ankylosis of teeth" },
  { id: "27", label: "K03.6", description: "Deposits [accretions] on teeth" },
  {
    id: "28",
    label: "K03.7",
    description: "Posteruptive colour changes of dental hard tissues",
  },
  {
    id: "29",
    label: "K03.8",
    description: "Other specified diseases of hard tissues of teeth",
  },
  {
    id: "30",
    label: "K03.9",
    description: "Disease of hard tissues of teeth, unspecified",
  },
  { id: "31", label: "K04.0", description: "Pulpitis" },
  { id: "32", label: "K04.1", description: "Necrosis of pulp" },
  { id: "33", label: "K04.2", description: "Pulp degeneration" },
  {
    id: "34",
    label: "K04.3",
    description: "Abnormal hard tissue formation in pulp",
  },
  {
    id: "35",
    label: "K04.4",
    description: "Acute apical periodontitis of pulpal origin",
  },
  { id: "36", label: "K04.5", description: "Chronic apical periodontitis" },
  { id: "37", label: "K04.6", description: "Periapical abscess with sinus" },
  { id: "38", label: "K04.7", description: "Periapical abscess without sinus" },
  { id: "39", label: "K04.8", description: "Radicular cyst" },
  {
    id: "40",
    label: "K04.9",
    description:
      "Other and unspecified diseases of pulp and periapical tissues",
  },
  { id: "41", label: "K05.0", description: "Acute gingivitis" },
  { id: "42", label: "K05.1", description: "Chronic gingivitis" },
  { id: "43", label: "K05.2", description: "Acute periodontitis" },
  { id: "44", label: "K05.3", description: "Chronic periodontitis" },
  { id: "45", label: "K05.4", description: "Periodontosis" },
  { id: "46", label: "K05.5", description: "Other periodontal diseases" },
  { id: "47", label: "K05.6", description: "Periodontal disease, unspecified" },
  { id: "48", label: "K06.0", description: "Gingival recession" },
  { id: "49", label: "K06.1", description: "Gingival enlargement" },
  {
    id: "50",
    label: "K06.2",
    description:
      "Gingival and edentulous alveolar ridge lesions associated with trauma",
  },
  {
    id: "51",
    label: "K06.8",
    description:
      "Other specified disorders of gingiva and edentulous alveolar ridge",
  },
  {
    id: "52",
    label: "K06.9",
    description:
      "Disorder of gingiva and edentulous alveolar ridge, unspecified",
  },
  { id: "53", label: "K07.0", description: "Major anomalies of jaw size" },
  {
    id: "54",
    label: "K07.1",
    description: "Anomalies of jaw-cranial base relationship",
  },
  {
    id: "55",
    label: "K07.2",
    description: "Anomalies of dental arch relationship",
  },
  { id: "56", label: "K07.3", description: "Anomalies of tooth position" },
  { id: "57", label: "K07.4", description: "Malocclusion, unspecified" },
  {
    id: "58",
    label: "K07.5",
    description: "Dentofacial functional abnormalities",
  },
  {
    id: "59",
    label: "K07.6",
    description: "Temporomandibular joint disorders",
  },
  { id: "60", label: "K07.8", description: "Other dentofacial anomalies" },
  { id: "61", label: "K07.9", description: "Dentofacial anomaly, unspecified" },
  {
    id: "62",
    label: "K08.0",
    description: "Exfoliation of teeth due to systemic causes",
  },
  {
    id: "63",
    label: "K08.1",
    description:
      "Loss of teeth due to accident, extraction or local periodontal disease",
  },
  {
    id: "64",
    label: "K08.2",
    description: "Atrophy of edentulous alveolar ridge",
  },
  { id: "65", label: "K08.3", description: "Retained dental root" },
  {
    id: "66",
    label: "K08.8",
    description: "Other specified disorders of teeth and supporting structures",
  },
  {
    id: "67",
    label: "K08.9",
    description: "Disorder of teeth and supporting structures, unspecified",
  },
  { id: "68", label: "K09.0", description: "Developmental odontogenic cysts" },
  {
    id: "69",
    label: "K09.1",
    description: "Developmental (nonodontogenic) cysts of oral region",
  },
  { id: "70", label: "K09.2", description: "Other cysts of jaw" },
  {
    id: "71",
    label: "K09.8",
    description: "Other cysts of oral region, not elsewhere classified",
  },
  { id: "72", label: "K09.9", description: "Cyst of oral region, unspecified" },
  { id: "73", label: "K10.0", description: "Developmental disorders of jaws" },
  { id: "74", label: "K10.1", description: "Giant cell granuloma, central" },
  { id: "75", label: "K10.2", description: "Inflammatory conditions of jaws" },
  { id: "76", label: "K10.3", description: "Alveolitis of jaws" },
  { id: "77", label: "K10.8", description: "Other specified diseases of jaws" },
  { id: "78", label: "K10.9", description: "Disease of jaws, unspecified" },
  { id: "79", label: "K11.0", description: "Atrophy of salivary gland" },
  { id: "80", label: "K11.1", description: "Hypertrophy of salivary gland" },
  { id: "81", label: "K11.2", description: "Sialoadenitis" },
  { id: "82", label: "K11.3", description: "Abscess of salivary gland" },
  { id: "83", label: "K11.4", description: "Fistula of salivary gland" },
  { id: "84", label: "K11.5", description: "Sialolithiasis" },
  { id: "85", label: "K11.6", description: "Mucocele of salivary gland" },
  {
    id: "86",
    label: "K11.7",
    description: "Disturbances of salivary secretion",
  },
  {
    id: "87",
    label: "K11.8",
    description: "Other diseases of salivary glands",
  },
  {
    id: "88",
    label: "K11.9",
    description: "Disease of salivary gland, unspecified",
  },
  { id: "89", label: "K12.0", description: "Recurrent oral aphthae" },
  { id: "90", label: "K12.1", description: "Other forms of stomatitis" },
  { id: "91", label: "K12.2", description: "Cellulitis and abscess of mouth" },
  { id: "92", label: "K12.3", description: "Oral mucositis (ulcerative)" },
  { id: "93", label: "K13.0", description: "Diseases of lips" },
  { id: "94", label: "K13.1", description: "Cheek and lip biting" },
  {
    id: "95",
    label: "K13.2",
    description:
      "Leukoplakia and other disturbances of oral epithelium, including tongue",
  },
  { id: "96", label: "K13.3", description: "Hairy leukoplakia" },
  {
    id: "97",
    label: "K13.4",
    description: "Granuloma and granuloma-like lesions of oral mucosa",
  },
  { id: "98", label: "K13.5", description: "Oral submucous fibrosis" },
  {
    id: "99",
    label: "K13.6",
    description: "Irritative hyperplasia of oral mucosa",
  },
  {
    id: "100",
    label: "K13.7",
    description: "Other and unspecified lesions of oral mucosa",
  },
  { id: "101", label: "K14.0", description: "Glossitis" },
  { id: "102", label: "K14.1", description: "Geographic tongue" },
  { id: "103", label: "K14.2", description: "Median rhomboid glossitis" },
  { id: "104", label: "K14.3", description: "Hypertrophy of tongue papillae" },
  { id: "105", label: "K14.4", description: "Atrophy of tongue papillae" },
  { id: "106", label: "K14.5", description: "Plicated tongue" },
  { id: "117", label: "K14.6", description: "Glossodynia" },
  { id: "108", label: "K14.8", description: "Other diseases of tongue" },
  { id: "109", label: "K14.9", description: "Disease of tongue, unspecified" },
];
