import { Platform, StyleSheet } from "react-native";
import colors from "../../../styles/colors";
import {
  moderateScale,
  scale,
  textScale,
  verticalScale,
} from "../../../styles/responsiveSize";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  box: {
    width: "100%",
    height: moderateScale(161),
    backgroundColor: colors.secondary,
    paddingHorizontal: scale(20),
    justifyContent: "center",
    alignItems: "center",
  },
  box2: {
    height: moderateScale(200),
    backgroundColor: colors.secondary,
    paddingHorizontal: scale(20),
  },
  patientText: {
    fontSize: textScale(30),
    color: colors.white,
    fontWeight: "600",
    fontFamily: "Inter-Bold",
    textAlign: "center",
    paddingTop: verticalScale(70),
  },
  searchBar: {
    width: moderateScale(340),
    height: moderateScale(50),
    borderWidth: 1,
    borderColor: colors.gray02,
    backgroundColor: colors.white,
    borderRadius: moderateScale(25),
    alignSelf: "center",
    marginTop: verticalScale(20),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
  },
  container5: {
    flexDirection: "row",
    marginTop: verticalScale(17),
    justifyContent: "space-between",
    alignItems: "center",
  },
  save: {
    fontSize: textScale(20),
    color: colors.white,
    fontWeight: "600",
  },
  imageStyle: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.white,
  },
  profileImageContainer: {
    width: moderateScale(158),
    height: moderateScale(158),
    borderRadius: moderateScale(79),
    backgroundColor: colors.white,
    alignSelf: "center",
    top: verticalScale(125),
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 3,
    shadowRadius: 3,
    elevation: 2,
  },
  profileimageStyle: {
    width: moderateScale(150),
    height: moderateScale(150),
    borderRadius: moderateScale(75),
  },
  box3: {
    width: moderateScale(343),
    height: moderateScale(50),
    backgroundColor: colors.gray01,
    borderWidth: 1,
    borderColor: colors.gray02,
    borderRadius: moderateScale(25),
    alignSelf: "center",
    marginTop: verticalScale(18),
    flexDirection: "row",
  },

  informationContainer: {
    width: moderateScale(171),
    height: moderateScale(46),
    borderRadius: moderateScale(25),
    justifyContent: "center",
    alignItems: "center",
  },
  whatsAppContainer: {
    alignSelf: "center",
  },
  openWhatsapp: {
    fontSize: textScale(16),
    color: colors.secondary,
    textDecorationLine: "underline",
    paddingTop: verticalScale(10),
  },
  whatsApp: {
    width: moderateScale(75),
    height: moderateScale(75),
  },
  modalStyle: {
    height: moderateScale(300),
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
    justifyContent: "center",
    alignItems: "center",
  },
  modalStyle4: {
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
  },
  modalStyle3: {
    height: moderateScale(300),
    width: "100%",
    paddingTop: verticalScale(20),
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
    paddingHorizontal: scale(16),
  },
  modalStyle2: {
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
  },
  title: {
    paddingTop: verticalScale(10),
    fontSize: textScale(16),
    fontWeight: "700",
    color: colors.black,
    paddingHorizontal: scale(16),
  },
  textInputColor: {
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
  },
  medicalTreatmentCont: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: verticalScale(5),
  },
  plusStyle: { width: 15, height: 15, marginRight: scale(16) },
  container3: {
    padding: scale(10),
    width: moderateScale(341),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.gray02,
    backgroundColor: colors.gray01,
    marginTop: verticalScale(5),
    alignSelf: "center",
  },
  totalText: {
    textAlign: "right",
    paddingRight: scale(50),
    fontSize: textScale(16),
    color: colors.black,
    fontWeight: "bold",
    paddingBottom: verticalScale(10),
  },
  CheckBoxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: verticalScale(10),
  },
  sentence: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.black,
    paddingLeft: scale(15),
  },
  addContainer: {
    width: moderateScale(327),
    marginTop: 0,
  },
  cancelButton: {
    marginTop: verticalScale(-5),
    backgroundColor: "transparent",
  },
  cancelButtonLabel: {
    color: colors.primary,
  },
  arrowImage: {
    width: moderateScale(20),
    height: moderateScale(20),
    alignSelf: "flex-start",
  },
  buttonStyle: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: scale(5),
    height: 70,
    alignItems: "center",
  },
  buttonLayout: {
    width: moderateScale(150),
    backgroundColor: colors.brown,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  buttonLayout2: {
    width: moderateScale(165),
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  useTemplate: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.lightBlue,
    paddingHorizontal: scale(16),
  },
  medicalTreatmentCont: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: verticalScale(5),
  },
  findMedication: {
    width: moderateScale(327),
    borderRadius: moderateScale(10),
    backgroundColor: colors.gray01,
  },
  quantityInstuction: {
    width: moderateScale(150),
    borderRadius: moderateScale(10),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
  },
  quantityInstuction2: {
    width: moderateScale(150),
    borderRadius: moderateScale(10),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
    marginLeft: scale(27),
  },
  dash: {
    fontSize: textScale(80),
    fontWeight: "500",
    color: colors.white,
    textAlign: "center",
  },
  inputName: {
    textAlign: "center",
    color: colors.black,
    fontSize: textScale(30),
    fontWeight: "bold",
    paddingTop: verticalScale(12),
  },
  containerOfName: {
    backgroundColor: "transparent",
    borderWidth: 0,
    marginTop: Platform.OS === "ios" ? verticalScale(0) : verticalScale(30),
  },
  addImage: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.white,
  },
  addImageContainer: {
    width: moderateScale(35),
    height: moderateScale(35),
    borderRadius: moderateScale(35),
    backgroundColor: colors.secondary,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: verticalScale(-5),
    right: scale(15),
  },
  patientsList: {
    height: moderateScale(400),
    marginHorizontal: scale(20),
    marginTop: verticalScale(20),
  },
  patientCard: {
    height: moderateScale(70),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 0.5,
    borderColor: colors.gray02,
    flex: 1,
  },
  profileImageOfPatient: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: colors.gray01,
  },
  profileImageStyle: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
  },
  patientNameContainer: {
    flex: 1,
    paddingHorizontal: scale(10),
  },
  patientName: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.black,
  },
  emptyPatientContainer: {
    height: moderateScale(400),
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: scale(20),
    marginVertical: verticalScale(20),
  },
  emptyPatient: {
    width: moderateScale(200),
    height: moderateScale(200),
  },
  emptyPatientLine: {
    fontSize: textScale(12),
    fontWeight: "500",
    textAlign: "center",
    color: colors.gray03,
    paddingHorizontal: scale(16),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  dateOfBirthPlace: {
    fontSize: textScale(12),
    fontWeight: "500",
    color: colors.gray03,
    paddingTop: verticalScale(5),
  },

  iconStyle: {
    width: scale(20),
    height: verticalScale(20),
  },
  iconText: {
    marginHorizontal: scale(25),
    marginTop: verticalScale(20),
    backgroundColor: colors.white,
    flexDirection: "row",

    alignItems: "center",
  },
  textOfGender: {
    flex: 1,
    fontSize: textScale(16),
    color: colors.gray03,
    paddingHorizontal: scale(16),
  },

  checkbox: {
    width: moderateScale(20),
    height: moderateScale(20),
  },
  firstContainer: {
    marginHorizontal: scale(20),
    marginTop: verticalScale(20),
  },
  selectSex: {
    fontSize: textScale(16),
    fontWeight: "bold",
    color: colors.black,
  },
  leftArrow: {
    width: moderateScale(25),
    height: moderateScale(25),
  },
  editInfo: {
    width: moderateScale(25),
    height: moderateScale(25),
  },
  flatListContainerStyle: {
    flex: 1,
    backgroundColor: colors.gray01,
    borderRadius: moderateScale(8),
  },
  totalText: {
    textAlign: "right",
    paddingRight: scale(10),
    fontSize: textScale(16),
    color: colors.black,
    fontWeight: "bold",
    paddingVertical: verticalScale(5),
  },
  sentence: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.black,
    paddingLeft: scale(15),
  },
  flatListContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: moderateScale(16),
    borderTopRightRadius: moderateScale(16),
  },
  headerContainer: {
    marginHorizontal: scale(20),
    height: moderateScale(50),
    alignItems: "center",
    justifyContent: "space-between",
    alignSelf: "center",
    backgroundColor: colors.white,
    width: moderateScale(323),
    flexDirection: "row",
    marginTop: verticalScale(12),
  },
  arrowStyle2: {
    width: moderateScale(20),
    height: moderateScale(20),
  },
  profileTextStyle: {
    fontSize: textScale(18),
    fontWeight: "bold",
    color: colors.black,
  },
  profileImageContainer2: {
    width: moderateScale(158),
    height: moderateScale(158),
    borderRadius: moderateScale(79),
    backgroundColor: colors.white,
    alignSelf: "center",
    marginTop: verticalScale(10),
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 3,
    shadowRadius: 3,
    elevation: 2,
  },
  inputName2: {
    flex: 1,
    textAlign: "center",
    color: colors.black,
    fontSize: textScale(30),
    fontWeight: "bold",
    paddingTop: verticalScale(12),
  },
  deleteContainer: {
    width: moderateScale(18),
    height: moderateScale(18),
    tintColor: colors.red,
  },
  templateTitle2: {
    justifyContent: "space-between",
    // alignItems: 'center',
    width: moderateScale(327),
    // height: moderateScale(50),
    borderRadius: moderateScale(30),
    paddingHorizontal: scale(16),
    backgroundColor: colors.white,
    marginTop: verticalScale(20),
    alignSelf: "center",
    borderRadius: moderateScale(8),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  arrowStyle: {
    width: moderateScale(12),
    height: moderateScale(12),
  },
  heading: {
    fontSize: textScale(16),
    fontWeight: "700",
    color: colors.black,
  },
  fourPhotoContainer: {
    width: moderateScale(343),
    flexDirection: "row",
    alignItems: "center",
    marginTop: verticalScale(20),
    backgroundColor: colors.gray01,
    padding: scale(10),
    borderRadius: moderateScale(8),
    flexWrap: "wrap",
  },
  medicationList: {
    width: moderateScale(327),
    height: moderateScale(100),
    backgroundColor: colors.white,
    alignSelf: "center",
    borderRadius: moderateScale(10),
    borderWidth: 0.5,
    borderColor: colors.gray03,
    marginBottom: verticalScale(10),
  },
  medicationItem: {
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(10),
  },
  medicationItemText: {
    fontSize: 16,
    color: "black",
  },
  dateRangeSelect: {
    fontSize: textScale(16),
    fontWeight: "bold",
    color: colors.black,
    paddingVertical: scale(16),
    textAlign: "center",
  },
  dateStyleText: {
    fontSize: textScale(14),
    fontWeight: "500",
    color: colors.black,
    paddingHorizontal: scale(16),
  },
  textInputContainer2: {
    backgroundColor: colors.gray01,
    width: moderateScale(300),
    marginTop: verticalScale(10),
    height: moderateScale(50),
  },
  inputStyle2: {
    fontSize: textScale(18),
    paddingHorizontal: scale(5),
    color: colors.black,
    fontWeight: "800",
  },
  iconContainer: {
    height: moderateScale(20),
    width: moderateScale(20),
    // marginTop: verticalScale(20),
  },
  iconStyle3: {
    height: moderateScale(20),
    width: moderateScale(20),
  },
  noDataContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
  },
  noDataImage2: {
    width: moderateScale(100),
    height: moderateScale(100),
  },
  noSetupText: {
    fontSize: textScale(12),
    fontWeight: "500",
    color: colors.gray03,
    textAlign: "center",
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(20),
  },
  cameraContainer: {
    width: moderateScale(30),
    height: moderateScale(30),
    borderRadius: moderateScale(8),
    marginLeft: scale(10),
  },
  cameraContainer2: {
    width: moderateScale(90),
    height: moderateScale(90),
    borderRadius: moderateScale(8),
    marginLeft: scale(10),
    marginTop: verticalScale(2),
  },
  itemImages: {
    width: moderateScale(90),
    height: moderateScale(90),
    borderRadius: moderateScale(8),
  },
  objectivesContainer: {
    width: moderateScale(343),
    height: moderateScale(100),
    backgroundColor: colors.gray01,
    alignSelf: "center",
    borderRadius: moderateScale(8),
    borderWidth: 0.5,
    borderColor: colors.gray03,
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(10),
  },
  objectiveItemContainer: {
    paddingVertical: verticalScale(3),
  },
  objectiveItemTitle: {
    fontSize: textScale(14),
    fontWeight: "300",
    color: colors.black,
  },
  layoutContainerDelete: {
    width: moderateScale(15),
    height: moderateScale(15),
    position: "absolute",
    top: verticalScale(-4),
    right: scale(-4),
  },
  deleteContainerImage: {
    width: moderateScale(15),
    height: moderateScale(15),
  },
  findMedication2: {
    color: colors.black,
    fontSize: textScale(12),
    fontWeight: "500",
  },
  quantity: {
    color: colors.gray03,
    fontSize: textScale(12),
    textAlign: "left",
    paddingLeft: scale(16),
  },
  medicationContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: verticalScale(5),
  },

  editIconImage: {
    width: moderateScale(14),
    height: moderateScale(14),
    marginLeft: scale(10),
  },
  noResultFound: {
    fontSize: textScale(16),
    color: colors.black,
  },
  objectiveItemContainer: {
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(10),
  },
  objectiveItemTitle: {
    fontSize: textScale(16),
    color: "black",
  },
  patientNameItemContainer: {
    width: moderateScale(327),
    height: moderateScale(100),
    backgroundColor: colors.white,
    alignSelf: "center",
    borderRadius: moderateScale(10),
    borderWidth: 0.5,
    borderColor: colors.gray03,
    marginBottom: verticalScale(10),
  },
  bottomContainer: {
    backgroundColor: colors.white,
    padding: moderateScale(16),
    borderTopLeftRadius: moderateScale(10),
    borderTopRightRadius: moderateScale(10),
  },
  position: {
    marginLeft: scale(16),
    marginRight: scale(16),
  },
  boxTouch: {
    height: 30,
    width: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  searchInput: {
    backgroundColor: "white",
    paddingHorizontal: 10,
    borderRadius: 5,
    marginBottom: 10,
    fontSize: 16,
  },
});

export default styles;
