import {Platform, StyleSheet} from 'react-native';
import {
  moderateScale,
  scale,
  textScale,
  verticalScale,
} from '../../../styles/responsiveSize';
const {default: colors} = require('../../../styles/colors');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  box: {
    width: '100%',
    height: moderateScale(215),
    backgroundColor: colors.secondary,
    paddingHorizontal: scale(20),
  },
  signOut: {
    fontSize: textScale(16),
    color: colors.white,
    fontWeight: '600',
  },
  doctorName: {
    fontSize: textScale(18),
    color: colors.secondary,
    fontWeight: '600',
    paddingLeft: scale(10),
  },
  doctorName2: {
    fontSize: textScale(32),
    color: colors.white,
    fontWeight: '600',
    paddingLeft: scale(10),
    paddingTop: verticalScale(80),
  },
  profileImageContainer: {
    position: 'absolute',
    width: moderateScale(158),
    height: moderateScale(158),
    borderRadius: moderateScale(79),
    backgroundColor: colors.white,
    bottom: verticalScale(-79),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 3,
    shadowRadius: 3,
    elevation: 2,
  },
  profileStyle2: {
    width: '96%',
    height: '96%',
    borderRadius: moderateScale(79),
  },
  doctorDetailContainer: {
    width: moderateScale(344),
    backgroundColor: colors.white,
    alignSelf: 'center',
    marginTop: verticalScale(10),
    borderRadius: moderateScale(8),
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },

  contentOfDoctor: {
    flexDirection: 'row',
    marginHorizontal: scale(15),
    marginVertical: verticalScale(12),
    alignItems: 'center',
  },
  iconStyle: {
    width: moderateScale(30),
    height: moderateScale(30),
  },
  labelStyle: {
    fontSize: textScale(20),
    fontWeight: '500',
    color: colors.black,
    paddingLeft: scale(15),
  },
  medicalTreatment: {
    fontSize: textScale(30),
    fontWeight: '600',
    color: colors.white,
    textAlign: 'center',
    marginTop: verticalScale(20),
  },
  medicalTreatmentList: {
    alignItems: 'center',
    paddingVertical: verticalScale(20),
    borderBottomWidth: 1,
    borderColor: colors.gray02,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  medicalTreatmentListText: {
    fontSize: textScale(16),
    fontWeight: '500',
    color: colors.black,
  },

  textInputContainer: {
    backgroundColor: colors.gray01,
    width: moderateScale(312),
    marginTop: verticalScale(10),
    // height: moderateScale(50),
  },
  container1: {
    marginHorizontal: scale(16),
    marginTop: verticalScale(20),
  },
  keyBoardAwareStyle: {
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
    marginTop: verticalScale(200),
  },
  heading: {
    fontSize: textScale(16),
    fontWeight: '700',
    color: colors.black,
  },
  addButton: {
    marginTop: verticalScale(10),
  },
  cancelButton: {
    marginTop: verticalScale(-5),
    backgroundColor: 'transparent',
  },
  cancelButtonLabel: {
    color: colors.primary,
  },
  arrowImage: {
    width: moderateScale(20),
    height: moderateScale(20),
    alignSelf: 'flex-start',
  },
  modalStyle: {
    height: moderateScale(300),
    width: '100%',
    paddingTop: verticalScale(20),
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
    paddingHorizontal: scale(16),
  },
  modalStyle2: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
  },

  textInputColor: {
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
  },
  title: {
    paddingTop: verticalScale(10),
    fontSize: textScale(16),
    fontWeight: '700',
    color: colors.black,
    paddingHorizontal: scale(16),
  },
  buttonStyle: {
    flexDirection: 'row',
  },
  buttonLayout: {
    width: moderateScale(165),
    backgroundColor: colors.brown,
  },
  buttonLayout2: {
    width: moderateScale(165),
  },
  CheckBoxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(5),
  },
  sentence: {
    fontSize: textScale(16),
    fontWeight: '500',
    color: colors.black,
    paddingLeft: scale(15),
  },
  medicalTreatmentCont: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: verticalScale(5),
  },

  container3: {
    width: moderateScale(341),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.gray02,
    backgroundColor: colors.gray01,
    marginTop: verticalScale(5),
    alignSelf: 'center',
    padding: scale(10),
  },
  totalText: {
    textAlign: 'right',
    paddingRight: scale(10),
    fontSize: textScale(16),
    color: colors.black,
    fontWeight: 'bold',
    paddingVertical: verticalScale(5),
  },
  plusStyle: {width: 15, height: 15, marginRight: scale(16)},
  findMedication: {
    width: moderateScale(327),
    borderRadius: moderateScale(10),
    backgroundColor: colors.gray01,
  },
  quantityInstuction: {
    width: moderateScale(135),
    borderRadius: moderateScale(10),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
  },
  quantityInstuction2: {
    width: moderateScale(150),
    borderRadius: moderateScale(10),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
    marginLeft: scale(27),
  },
  signOutCont: {
    alignSelf: 'flex-end',
    top: verticalScale(50),
  },
  logoutStyle: {
    width: moderateScale(28),
    height: moderateScale(28),
  },
  container5: {
    flexDirection: 'row',
    marginTop: verticalScale(17),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftArrow: {
    width: moderateScale(25),
    height: moderateScale(25),
  },
  containerOfName: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginTop: Platform.OS === 'ios' ? verticalScale(0) : verticalScale(30),
  },
  inputName: {
    textAlign: 'center',
    color: colors.white,
    fontSize: textScale(30),
    fontWeight: 'bold',
  },
  flatListContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: moderateScale(16),
    borderTopRightRadius: moderateScale(16),
  },
  noDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  noDataImage: {
    width: moderateScale(250),
    height: moderateScale(250),
  },
  noSetupText: {
    fontSize: textScale(12),
    fontWeight: '500',
    color: colors.gray03,
    textAlign: 'center',
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(20),
  },
  checkbox: {
    width: moderateScale(15),
    height: moderateScale(15),
  },
  addContainer: {
    marginTop: verticalScale(0),
  },
  flatListContainerStyle: {
    flex: 1,
    backgroundColor: colors.gray01,
    borderRadius: moderateScale(8),
  },
  medicationContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',

    paddingTop: verticalScale(5),
  },
  findMedication2: {
    color: colors.black,
    fontSize: textScale(12),
    fontWeight: '500',
  },
  quantity: {
    color: colors.gray03,
    fontSize: textScale(12),
    textAlign: 'left',
    paddingLeft: scale(16),
  },
  templateTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: moderateScale(327),
    borderRadius: moderateScale(30),
    paddingHorizontal: scale(16),
    backgroundColor: colors.white,
    marginTop: verticalScale(20),
    alignSelf: 'center',
    borderRadius: moderateScale(8),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  templateTitle2: {
    width: moderateScale(327),
    borderRadius: moderateScale(30),
    paddingHorizontal: scale(16),
    backgroundColor: colors.white,
    marginTop: verticalScale(20),
    alignSelf: 'center',
    borderRadius: moderateScale(8),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  arrowStyle: {
    width: moderateScale(12),
    height: moderateScale(12),
  },
  editIconImage: {
    width: moderateScale(14),
    height: moderateScale(14),
  },
  noDataImage2: {
    width: moderateScale(100),
    height: moderateScale(100),
  },
  arrowBackCont: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(10),
    marginLeft: scale(16),
  },
  headerContainer: {
    marginHorizontal: scale(20),
    height: moderateScale(50),
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    backgroundColor: colors.white,
    width: moderateScale(323),
    flexDirection: 'row',
    marginTop: verticalScale(12),
  },
  arrowStyle2: {
    width: moderateScale(20),
    height: moderateScale(20),
  },
  profileTextStyle: {
    fontSize: textScale(18),
    fontWeight: 'bold',
    color: colors.black,
  },
  profileBox: {
    width: moderateScale(323),
    borderRadius: moderateScale(12),
    backgroundColor: colors.white,
    shadowColor: colors.black,
    alignSelf: 'center',
    shadowRadius: 3,
    elevation: 5,
    shadowOpacity: 6,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    marginTop: verticalScale(10),
  },
  profileImageAndDetailCont: {
    flexDirection: 'row',
    marginHorizontal: scale(16),
    marginVertical: verticalScale(16),
  },
  profileContainer: {
    width: moderateScale(70),
    height: moderateScale(70),
    borderRadius: moderateScale(10),
    backgroundColor: colors.white,
  },
  profileStyle: {
    width: '100%',
    height: '100%',
    borderRadius: moderateScale(10),
  },
  emailStyle: {
    fontSize: textScale(12),
    paddingLeft: scale(10),
    paddingTop: verticalScale(3),
    color: colors.gray03,
  },
  verifiedContainer: {
    height: moderateScale(25),
    width: moderateScale(50),
    borderRadius: moderateScale(20),
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: scale(10),
    marginTop: verticalScale(3),
  },
  verifyTextStyle: {
    fontSize: textScale(10),
    color: colors.white,
  },
  profileOptionsContainer: {
    height: moderateScale(50),
    width: moderateScale(323),
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    marginTop: verticalScale(10),

    borderColor: colors.gray03,
  },
  profileOptionsText: {
    fontSize: textScale(14),
    color: colors.black,
    fontWeight: '600',
    paddingLeft: scale(15),
  },
  rightSideIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
  },
  leftSideIcon: {
    width: moderateScale(15),
    height: moderateScale(15),
  },
  medicationList: {
    width: moderateScale(327),
    height: moderateScale(100),
    backgroundColor: colors.white,
    alignSelf: 'center',
    borderRadius: moderateScale(10),
    borderWidth: 0.5,
    borderColor: colors.gray03,
    marginBottom: verticalScale(10),
  },
  medicationItem: {
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(10),
  },
  medicationItemText: {
    fontSize: textScale(16),
    color: colors.black,
  },
  deleteContainer: {
    width: moderateScale(18),
    height: moderateScale(18),
    tintColor: colors.red,
  },
  objectivesContainer: {
    width: moderateScale(343),
    height: moderateScale(100),
    backgroundColor: colors.gray01,
    alignSelf: 'center',
    borderRadius: moderateScale(8),
    borderWidth: 0.5,
    borderColor: colors.gray03,
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(10),
  },
  objectiveItemContainer: {
    paddingVertical: verticalScale(3),
  },
  objectiveItemTitle: {
    fontSize: textScale(14),
    fontWeight: '300',
    color: colors.black,
  },
  searchInput: {
    backgroundColor: 'white', 
    paddingHorizontal: 10, 
    borderRadius: 5, 
    marginBottom: 10, 
    fontSize: 16, 
  },
  modalStyle3: {
    height: moderateScale(300),
    width: '100%',
    paddingTop: verticalScale(20),
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
    paddingHorizontal: scale(16),
  },
});
export default styles;
