import { Platform, StyleSheet } from "react-native";
import colors from "../../styles/colors";
import {
  moderateScale,
  scale,
  textScale,
  verticalScale,
} from "../../styles/responsiveSize";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    paddingTop: verticalScale(16),
  },
  headingStyle: {
    fontSize: textScale(20),
    fontWeight: "bold",
    color: colors.black,
    textAlign: "center",
    marginTop: verticalScale(16),
    marginBottom: verticalScale(16),
  },

  forgotPasswordText: {
    fontSize: textScale(16),
    color: colors.lightBlue,
    textAlign: "right",
  },
  forgotPasswordContainer: {
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
  },

  textualStyle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subHeadingStyle: {
    paddingRight: scale(16),
    fontSize: textScale(18),
    fontWeight: "600",
    color: colors.lightBlue,
  },
  imageLogoStyle: {
    position: "absolute",
    width: moderateScale(150),
    height: moderateScale(150),
    right: scale(10),
    // top: verticalScale(80),
    marginTop: Platform.OS === "ios" ? verticalScale(80) : verticalScale(30),
  },
  imageStyle: {
    width: "100%",
    height: "100%",
  },
  successMessageContainer: {
    height: verticalScale(212),
    marginTop: verticalScale(20),
    marginHorizontal: scale(16),
    borderRadius: moderateScale(8),
    justifyContent: "center",
    alignItems: "center",
  },
  thankuNote: {
    textAlign: "center",
    fontSize: textScale(14),
    color: colors.textBlack,
  },
  doctorName: {
    fontSize: textScale(30),
    fontWeight: "600",
    color: colors.white,
    textAlign: "center",
    paddingTop: verticalScale(10),
  },

  //// Check and remove
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  box: {
    width: "100%",
    height: moderateScale(161),
    backgroundColor: colors.secondary,
    paddingHorizontal: scale(20),
    justifyContent: "center",
    alignItems: "center",
  },
  box2: {
    height: moderateScale(200),
    backgroundColor: colors.secondary,
    paddingHorizontal: scale(20),
  },
  patientText: {
    fontSize: textScale(30),
    color: colors.white,
    fontWeight: "600",
    fontFamily: "Inter-Bold",
    textAlign: "center",
    marginTop: verticalScale(40),
  },
  searchBar: {
    width: moderateScale(340),
    height: moderateScale(50),
    borderWidth: 1,
    borderColor: colors.gray02,
    backgroundColor: colors.white,
    borderRadius: moderateScale(25),
    alignSelf: "center",
    marginTop: verticalScale(20),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
  },
  container5: {
    flexDirection: "row",
    marginTop: verticalScale(17),
    justifyContent: "space-between",
    alignItems: "center",
  },
  save: {
    fontSize: textScale(20),
    color: colors.white,
    fontWeight: "600",
  },
  imageStyle: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.white,
  },
  profileImageContainer: {
    width: moderateScale(158),
    height: moderateScale(158),
    borderRadius: moderateScale(79),
    backgroundColor: colors.white,
    alignSelf: "center",
    top: verticalScale(110),
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 3,
    shadowRadius: 3,
    elevation: 2,
  },
  profileImageContainer2: {
    width: moderateScale(158),
    height: moderateScale(158),
    borderRadius: moderateScale(79),
    marginTop: verticalScale(20),
    backgroundColor: colors.white,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 3,
    shadowRadius: 3,
    elevation: 2,
  },
  profileimageStyle: {
    width: moderateScale(150),
    height: moderateScale(150),
    borderRadius: moderateScale(75),
  },
  box3: {
    width: moderateScale(343),
    height: moderateScale(50),
    backgroundColor: colors.gray01,
    borderWidth: 1,
    borderColor: colors.gray02,
    borderRadius: moderateScale(25),
    alignSelf: "center",
    marginTop: verticalScale(18),
    flexDirection: "row",
  },

  informationContainer: {
    width: moderateScale(171),
    height: moderateScale(46),
    borderRadius: moderateScale(25),
    justifyContent: "center",
    alignItems: "center",
  },
  whatsAppContainer: {
    alignSelf: "center",
    marginTop: verticalScale(70),
  },
  openWhatsapp: {
    fontSize: textScale(16),
    color: colors.secondary,
    textDecorationLine: "underline",
    paddingTop: verticalScale(10),
  },
  whatsApp: {
    width: moderateScale(75),
    height: moderateScale(75),
  },
  modalStyle: {
    height: moderateScale(300),
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
    justifyContent: "center",
    alignItems: "center",
  },
  modalStyle2: {
    // height: moderateScale(300),
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: moderateScale(16),
  },
  title: {
    paddingTop: verticalScale(10),
    fontSize: textScale(16),
    fontWeight: "700",
    color: colors.black,
    paddingHorizontal: scale(16),
  },
  textInputColor: {
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
  },
  medicalTreatmentCont: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: verticalScale(5),
  },
  plusStyle: { width: 15, height: 15, marginRight: scale(16) },
  container3: {
    height: moderateScale(109),
    width: moderateScale(341),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.gray02,
    backgroundColor: colors.gray01,
    marginTop: verticalScale(5),
    alignSelf: "center",
  },
  totalText: {
    textAlign: "right",
    paddingRight: scale(50),
    fontSize: textScale(16),
    color: colors.black,
    fontWeight: "bold",
    paddingBottom: verticalScale(10),
  },
  CheckBoxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: verticalScale(10),
  },
  sentence: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.black,
    paddingLeft: scale(15),
  },
  addContainer: {
    width: moderateScale(327),
  },
  cancelButton: {
    marginTop: verticalScale(-5),
    backgroundColor: "transparent",
  },
  cancelButtonLabel: {
    color: colors.primary,
  },
  arrowImage: {
    width: moderateScale(20),
    height: moderateScale(20),
    alignSelf: "flex-start",
  },
  buttonStyle: {
    flexDirection: "row",
  },
  buttonLayout: {
    width: moderateScale(165),
    backgroundColor: colors.brown,
  },
  buttonLayout2: {
    width: moderateScale(165),
  },
  useTemplate: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.lightBlue,
    paddingHorizontal: scale(16),
  },
  medicalTreatmentCont: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: verticalScale(5),
  },
  findMedication: {
    width: moderateScale(327),
    borderRadius: moderateScale(30),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(0),
  },
  quantityInstuction: {
    width: moderateScale(150),
    borderRadius: moderateScale(30),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
  },
  quantityInstuction2: {
    width: moderateScale(150),
    borderRadius: moderateScale(30),
    backgroundColor: colors.gray01,
    marginTop: verticalScale(10),
    marginLeft: scale(27),
  },
  dash: {
    fontSize: textScale(80),
    fontWeight: "500",
    color: colors.white,
    textAlign: "center",
  },
  inputName: {
    textAlign: "center",
    color: colors.white,
    fontSize: textScale(30),
    fontWeight: "bold",
  },
  containerOfName: {
    backgroundColor: "transparent",
    borderWidth: 0,
    marginTop: Platform.OS === "ios" ? verticalScale(20) : verticalScale(30),
  },
  addImage: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.white,
  },
  addImageContainer: {
    width: moderateScale(35),
    height: moderateScale(35),
    borderRadius: moderateScale(35),
    backgroundColor: colors.secondary,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: verticalScale(-5),
    right: scale(15),
    zIndex: 999,
  },
  patientsList: {
    height: moderateScale(400),
    marginHorizontal: scale(20),
    marginVertical: verticalScale(20),
  },
  patientCard: {
    height: moderateScale(70),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 0.5,
    borderColor: colors.gray02,
  },
  profileImageOfPatient: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: colors.gray01,
  },
  profileImageStyle: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
  },
  patientNameContainer: {
    flex: 1,
    paddingHorizontal: scale(10),
  },
  patientName: {
    fontSize: textScale(16),
    fontWeight: "500",
    color: colors.black,
  },
  emptyPatientContainer: {
    height: moderateScale(400),
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: scale(20),
    marginVertical: verticalScale(20),
  },
  emptyPatient: {
    width: moderateScale(200),
    height: moderateScale(200),
  },
  emptyPatientLine: {
    fontSize: textScale(12),
    fontWeight: "500",
    textAlign: "center",
    color: colors.gray03,
    paddingHorizontal: scale(16),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  dateOfBirthPlace: {
    fontSize: textScale(12),
    fontWeight: "500",
    color: colors.gray03,
    paddingTop: verticalScale(5),
  },

  iconStyle: {
    width: scale(20),
    height: verticalScale(20),
  },
  iconText: {
    marginHorizontal: scale(25),
    marginTop: verticalScale(20),
    backgroundColor: colors.white,
    flexDirection: "row",

    alignItems: "center",
  },
  textOfGender: {
    flex: 1,
    fontSize: textScale(16),
    color: colors.gray03,
    paddingHorizontal: scale(16),
  },

  checkbox: {
    width: moderateScale(15),
    height: moderateScale(15),
  },
  firstContainer: {
    marginHorizontal: scale(20),
    marginTop: verticalScale(20),
  },
  selectSex: {
    fontSize: textScale(16),
    fontWeight: "bold",
    color: colors.black,
  },
  leftArrow: {
    width: moderateScale(25),
    height: moderateScale(25),
  },
  editInfo: {
    width: moderateScale(25),
    height: moderateScale(25),
  },
  logoContainer: {
    width: moderateScale(100),
    height: moderateScale(100),
    alignSelf: "center",
    marginTop: verticalScale(90),
    backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
  logoStyle: {
    width: moderateScale(100),
    height: moderateScale(100),
  },
  dontHaveAnAccountContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  textOfSignUp: {
    fontWeight: "bold",
    fontSize: textScale(16),
    color: colors.lightBlue,
    paddingLeft: scale(5),
  },
  textOfDontHaveAnAccount: {
    fontSize: textScale(16),
    color: colors.gray03,
  },
  createProfileText: {
    fontSize: textScale(20),
    fontWeight: "bold",
    color: colors.black,
    textAlign: "center",
    marginVertical: verticalScale(20),
  },
});

export default styles;
