export default {
  SIGN_IN: "Sign In",
  EMAIL: "Email",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password",
  SIGN_UP: "Sign Up",
  SHOW: "Show",
  FULL_NAME: "Full Name",
  PHONE_NUMBER: "Phone Number (WhatsApp)",
  CONFIRMATION: "Confirmation",
  MASUK: "Sign In",
  SUCCESSFUL_SIGN_UP: "Successful Sign-Up",
  THANK_YOU_FOR_SIGNING_UP:
    "Thank you for signing up. We will send a verification email with further instructions. Please check your spam folder if the email does not arrive within 10 minutes.",
  HOME: "Home",
  PATIENT: "Patient",
  PATIENTS: "Patients",
  AGENDA: "Agenda",
  ACCOUNT: "Account",
  CREATE: "Create",
  SCHEDULE: "Schedule",
  STATISTICS: "Statistics",
  SEE_AGENDA: "See Agenda",
  EXAMINATIONS: "Examinations",
  INCOME: "Income",
  SETUP_MEDICAL_TREATMENT: "Setup Medical Treatment",
  SETUP_TEMPLATE: "Setup Template",
  SIGN_OUT: "Sign Out",
  MEDICAL_TREATMENT: "Medical Treatment",
  CREATE_NEW_MEDICAL_TREATMENT: "Create New Medical Treatment",
  PRICE_PER_UNIT: "Price (per unit)",
  ADD: "Add",
  CANCEL: "Cancel",
  TEMPLATE: "Template",
  CREATE_NEW_TEMPLATE: "Create New Template",
  EXAMINATION_TEMPLATE: "Examination Template",
  PRESCRIPTION_TEMPLATE: "Prescription Template",
  TREATMENT_PLAN_TEMPLATE: "Treatment Plan Template",
  TEMPLATE_NAME: "Template Name",
  PATIENT_ISSUE_SUBJECTIVE: "Patient Issue (Subjective)",
  PATIENT_ISSUE_OBJECTIVE: "Patient Issue (Objective)",
  ASSESSMENT_RESULT: "Assessment Result",
  NEXT_STEPS: "Next Steps (Planning)",
  TOTAL: "Total",
  PAYMENT_METHOD: "Payment Method",
  RECOMMENDATION_AND_PROHIBITION: "Recommendations & Restrictions",
  OTHER_NOTE: "Other Notes (Shared with Patient)",
  DOCTORS_PERSONAL_NOTE: "Doctor's Personal Note (Not Shared)",
  RESET: "Reset",
  SAVE: "Save",
  MEDICATION_LIST: "Medication List",
  FIND_MEDICATION: "Find Medication",
  QUANTITY: "Quantity",
  INSTRUCTIONS: "Instructions",
  CREATE_NEW_APPOINTMENT: "Create New Appointment",
  PATIENT_NAME: "Patient Name",
  DATE: "Date",
  START_TIME: "Start Time",
  FIND_PATIENT: "Find Patient (Name)",
  ADD_NEW_PATIENT: "Add New Patient",
  PATIENT_PROFILE: "Patient Profile",
  INFORMATION: "Information",
  MEDICAL_HISTORY: "Medical History",
  PLACE_DATE_OF_BIRTH: "Date of Birth",
  HOME_ADDRESS: "Home Address",
  OCCUPATION: "Occupation",
  SEX_AND_MEDICAL_HISTORY: "Sex and Medical History",
  KTP_PASSPORT_NUMBER: "KTP/Passport Number",
  NOTE: "Note",
  ADD_RECORD: "Add Record",
  CREATE_MEDICAL_HISTORY_REPORT: "Create Medical History Report (PDF)",
  CREATE_REPORT: "Create Report",
  USE_TEMPLATE: "Use Template",
  EXAMINATION: "Examination",
  PRESCRIPTION: "Prescription",
  TREATMENT_PLAN: "Treatment Plan",
  APPOINTMENT: "Appointment",
  DATE_OF_BIRTH: "Date of Birth",
  SEX: "Sex",
  EXAMINATION_DATE: "Examination Date",
  BACK: "Back",
  LOCATION: "Location",
  PERIOD: "Period",
  LOADING: "Loading...",
  EMAIL_ALREADY_IN_USE: "This email is already in use.",
  EMAIL_VERIFY: "You are already registered. Please verify your email.",
  ALL_FIELDS_ARE_REQUIRED: "All fields are required",
  NO_USER_FOUND: "No account found with the provided information",
  WRONG_PASSWORD: "Wrong password or email.",
  EMAIL_NOT_VERIFIED: "Please verify your email first to log in.",
  RESET_PASSWORD: "Reset Password",
  EMAIL_NOT_FOUND: "Email not found",
  EMAIL_SENT_SUCCESSFULLY: "Email sent successfully",
  HELLO_DOCTOR: "Hello Doctor ",
  APPOINTMENT_DATA_NOT_FOUND: "Appointment data not found in our database",
  USER_DOCUMENT_NOT_FOUND: "User document not found in our database",
  NO_USER_SIGN_IN: "No user signed in",
  INVALID_APPOINTMENT_ID: "Invalid appointment ID",
  USER_APPOINTMENTS_DATA_IS: "User appointment data is not an array",
  NO_APPOINTMENTS: "No Appointments",
  PATIENT_ADDED_SUCCESSFULLY: "Patient Added Successfully",
  UPLOAD_IMAGE: "Upload Image",
  TAKE_PHOTO: "Take Photo",
  PHOTO_UPLOAD_SUCCESSFUL: "Photo Upload Successful",
  LIST_OF_PATIENTS: "List of Patients",
  EMPTY_PATIENT_LINE:
    "Patient Portal: Helping doctors input patient data. Understanding your patients better improves service quality!",
  MALE: "Male",
  FEMALE: "Female",
  EDIT: "Edit",
  SELECT_SEX: "Select Gender",
  HYPERTENSION: "Hypertension",
  DIABETES: "Diabetes",
  NERVE_DAMAGE: "Nerve Damage",
  HEMORRHAGE: "Hemorrhage",
  ANEMIA: "Anemia",
  ASTHMA: "Asthma",
  CHEMOTERAPHY: "Chemotherapy",
  RADIOFREQUENCY_TREATMENT: "Radiofrequency Treatment",
  HERPES: "Herpes",
  HEPATITIS: "Hepatitis",
  TBC: "TBC",
  HEART_CONDITION: "Heart Condition",
  SELECT_MEDICAL_HISTORY: "Select Medical History",
  WRITE_NAME: "Write Name",
  OPEN_WHATSAPP: "Open WhatsApp",
  UPDATE_PROFILE: "Update Profile",
  SIP: "SIP",
  STR: "STR",
  ADDRESS: "Address",
  SAVED: "Saved",
  DOCTOR_INFO_NOT_FOUND: "Doctor information not found in our database",
  NO_PROFILE: "No profile ID found in our database",
  USER_DATA_NOT_FOUND: "User data not found in our database",
  EDIT_ACCOUNT: "Edit Account",
  MEDICAL_TREATMENT_ADDED_SUCCESSFULLY: "Medical treatment added successfully",
  NO_SETUP_MEDICAL_TREATMENT: "No setup found. Please create one first.",
  EXAMINATION_TEMPLATES: "Examination Templates",
  PRESCRIPTION_TEMPLATES: "Prescription Templates",
  TREATMENT_PLAN_TEMPLATES: "Treatment Plan Templates",
  UPDATE: "Update",
  PLEASE_SIGN_IN: "Please sign in to access your account",
  SIGN_UP_HERE: "Sign up here to create your account",
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  HAVE_AN_ACCOUNT: "Already have an account?",
  CHECK_YOUR_MAIL_BOX: "Check your email inbox",
  WE_HAVE_SENT_CONFIRMATION:
    "We have sent a confirmation email. Please check your spam folder if the email is not in your inbox.",
  YOU_DONOT_HAVE_ANY_APPOINTMENT: "No appointments today. Please create one.",
  CREATE_PROFILE: "Create Profile",
  NO_TEMPLATE_FOUND_PLEASE_CREATE_ONE: "No template found. Please create one.",
  PROFILE: "Profile",
  MY_INFORMATION: "My Information",
  MY_TEMPLATES: "My Templates",
  MY_APPOINTMENTS: "My Appointments",
  MY_PATIENTS: "My Patients",
  SETTING: "Settings",
  LOGOUT: "Logout",
  MEDICAL_TREATMENT_TEMPLATES: "Medical Treatment Templates",
  UPLOAD_UPTO_4_PHOTOS: "Please upload up to 4 photos",
  CREATE_TEMPLATE: "Create Template",
  YOU_DONT_HAVE_ANY_DATA: "No data found. Please create one.",
  SELECT_DATE_RANGE: "Select Date Range",
  START_DATE: "Start Date",
  END_DATE: "End Date",
  DATES_ARE_NOT_FOUND_OR_INVALID: "Dates not found or invalid",
  NO_RESULT_FOUND: "No results found...",
  DELETE_MESSAGE:
    "Are you sure you want to delete this patient? Deleting the patient will also delete all medical records.",
  VIEW: "View",
  SHARE: "Share (PDF)",
  DELETE: "Delete",
};
